# Generated by Django 5.1.6 on 2025-02-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_api_key_individual_national_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='user',
        ),
    ]
